version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=LinkCutter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=backwater
    depends_on:
      - redis
      - db

  redis:
    image: "redis:alpine"
    expose:
      - "6379"

  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: "LinkCutter"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "backwater"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
